# Generated by Django 5.2.3 on 2025-06-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_book_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
