# Generated by Django 5.2.3 on 2025-06-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_good_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='my_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='page_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
